/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package k_pos;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
/**
 *
 * @author Najmul
 */
public class installation extends javax.swing.JFrame {

    /**
     * Creates new form about_small
     */
    public installation() {
        initComponents();
        seticon();
        setDefaultCloseOperation(installation.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);//for shoeing this in center
        get_settings get=new get_settings();    
        String Company = get.Company;
        String Version = get.Version;
        footer.setText(Company+" "+Version);  
        import_button.setEnabled (false);
        login_button.setEnabled (false);
    }

     private void seticon(){   
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/fevicon.png")));
    }   
    
    String path= "Backup/db.sql";
    String filename;
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        footer = new javax.swing.JLabel();
        import_button = new javax.swing.JButton();
        success = new javax.swing.JLabel();
        activation_input = new javax.swing.JTextField();
        active_button = new javax.swing.JButton();
        ac_status = new javax.swing.JLabel();
        success1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("K-POS Installation");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("K-POS Installation");

        login_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        footer.setForeground(new java.awt.Color(102, 102, 102));
        footer.setText("Footer Text");

        import_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        import_button.setText("Import Database");
        import_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                import_buttonActionPerformed(evt);
            }
        });

        activation_input.setForeground(new java.awt.Color(102, 102, 102));
        activation_input.setText(" Enter Activation Key");
        activation_input.setToolTipText("Install Activation Key");
        activation_input.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(195, 195, 195), 1, true));
        activation_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                activation_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                activation_inputFocusLost(evt);
            }
        });
        activation_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activation_inputActionPerformed(evt);
            }
        });

        active_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        active_button.setText("Activate");
        active_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                active_buttonActionPerformed(evt);
            }
        });

        ac_status.setForeground(new java.awt.Color(102, 102, 102));
        ac_status.setText("Activated Status");

        success1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/k_pos/images/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Step 1 : Activation");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Step 2 : Import Database");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Step 3 : Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 300, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(import_button, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(activation_input, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(active_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(127, 127, 127)
                        .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(success1))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ac_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(footer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(success1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ac_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(activation_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(active_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(import_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(footer))
                    .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        login l= new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_login_buttonActionPerformed

    private void import_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_import_buttonActionPerformed
        //Restore Button
        String dbUserName = "root";// username
        String dbPassword = "";//Password

        String[] restoreCmd = new String[]{"C:/xampp/mysql/bin/mysql.exe ", "--user=" + dbUserName, "--password=", "-e", "source " + path};
        Process runtimProcess;
        try {
            runtimProcess = Runtime.getRuntime().exec(restoreCmd);
            int proceCom = runtimProcess.waitFor();
            if (proceCom==0) {
                success.setText("Restore Succussed");
            }else{
                success.setText("Can't Restore");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_import_buttonActionPerformed

    private void active_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_active_buttonActionPerformed
        // Install Activation Key
        get_settings get=new get_settings();
        String Activation_Key = get.Activation_Key;
        String Activation_Dir = get.Activation_Dir;  
        
        //Check IF Activated or Not
        File file = new File (Activation_Dir);
        String Ac_Key = activation_input.getText();
        try {              
            //Validate Activation Key                
            if(Ac_Key.equals(Activation_Key)){
                //Write Activation Key                    
                  try{
                    PrintWriter writer = new PrintWriter(Activation_Dir, "UTF-8");
                    writer.println(Ac_Key);
                    writer.close();
                    success.setText("Successfully Activated !");  
                    ac_status.setText("K-POS is Activated !");       
                    import_button.setEnabled (true);
                    login_button.setEnabled (true);
                  }   
                  catch(Exception e){
                      System.out.println(e);
                  }
            }
            else{
                import_button.setEnabled (false);
                login_button.setEnabled (false);
                success.setText("Wrong Activation Key !");
            } 
        } catch (Exception e) {            
            System.out.println(e);
        }
    }//GEN-LAST:event_active_buttonActionPerformed

    private void activation_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activation_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activation_inputActionPerformed

    private void activation_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_activation_inputFocusGained
        //Focus Gained
         if(activation_input.getText().equals(" Enter Activation Key")){
            activation_input.setText("");
            activation_input.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_activation_inputFocusGained

    private void activation_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_activation_inputFocusLost
        //Lost Focus
        if(activation_input.getText().trim().equals("")){
            activation_input.setText(" Enter Activation Key");
            activation_input.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_activation_inputFocusLost

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Windows Activated 
        get_settings get=new get_settings();
        String Activation_Key = get.Activation_Key;
        String Activation_Dir = get.Activation_Dir;   
        File file = new File (Activation_Dir);
        try {     
            if(file.exists()){                
                BufferedReader br = new BufferedReader(new FileReader(file));
                String st = br.readLine();
                if(st != null){
                   //Print ac.kp
                   //System.out.println(st);
                   if(st.equals(Activation_Key)){
                        ac_status.setText("K-POS is Activated !");
                        //Show First 8 Activation Key
                        activation_input.setText(st);
                        //Enable Import Button
                        import_button.setEnabled (true);
                        login_button.setEnabled (true);
                    }
                   else{
                       ac_status.setText("K-POS is Not Activated !");
                       import_button.setEnabled (false);
                       login_button.setEnabled (false);
                   }
                }
                else{
                    ac_status.setText("K-POS is Not Activated !");
                }              
            }
            else{
                ac_status.setText("Activation File Not Found !");
            }
        }
        catch(Exception e){
            ac_status.setText("K-POS is Not Activated !");
            System.out.println("Error with Acativation Code.");
        }
    }//GEN-LAST:event_formWindowActivated
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(installation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(installation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(installation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(installation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new installation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ac_status;
    private javax.swing.JTextField activation_input;
    private javax.swing.JButton active_button;
    private javax.swing.JLabel footer;
    private javax.swing.JButton import_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel success;
    private javax.swing.JLabel success1;
    // End of variables declaration//GEN-END:variables
}
